### ISSUE TITLE
Capistrano task fails with NullPointerException upon deployment

### ISSUE THREAD

**Issue by panasyuk** [alienfast/bamboozled-ruby-plugin#12]
Here's the deployment log.
```
simple	08-сен-2015 14:19:38	Build Deployment of 'release-1' on 'Staging' started building on agent Default Agent
simple	08-сен-2015 14:19:38	
simple	08-сен-2015 14:19:38	Build working directory is /opt/atlassian/var/bamboo/xml-data/build-dir/131073/11468801-11534337
simple	08-сен-2015 14:19:38	Executing build Deployment of 'release-1' on 'Staging'
simple	08-сен-2015 14:19:38	Starting task 'Clean working directory task' of type 'com.atlassian.bamboo.plugins.bamboo-artifact-downloader-plugin:cleanWorkingDirectoryTask'
simple	08-сен-2015 14:19:38	Cleaning working directory '/opt/atlassian/var/bamboo/xml-data/build-dir/131073/11468801-11534337'
simple	08-сен-2015 14:19:42	Finished task 'Clean working directory task' with result: Success
simple	08-сен-2015 14:19:42	Starting task 'Загрузка артифакта' of type 'com.atlassian.bamboo.plugins.bamboo-artifact-downloader-plugin:artifactdownloadertask'
simple	08-сен-2015 14:19:42	Preparing to download plan result WT-WEB-9 artifact: Shared artifact: [Staging Build], pattern: [**/*]
simple	08-сен-2015 14:19:52	Artifact [Staging Build] downloaded successfully in 10s to: /./artifact/
simple	08-сен-2015 14:19:52	Finished task 'Загрузка артифакта' with result: Success
simple	08-сен-2015 14:19:52	Starting task 'Развертывание приложение в окружение staging' of type 'com.alienfast.bamboozled.ruby.bamboozled-ruby-plugin:task.capistrano'
error	08-сен-2015 14:19:52	Error occurred while running Task 'Развертывание приложение в окружение staging(3)' of type com.alienfast.bamboozled.ruby.bamboozled-ruby-plugin:task.capistrano.
error	08-сен-2015 14:19:52	java.lang.NullPointerException
error	08-сен-2015 14:19:52		at com.alienfast.bamboozled.ruby.tasks.AbstractRubyTask.execute(AbstractRubyTask.java:72)
error	08-сен-2015 14:19:52		at com.atlassian.bamboo.task.TaskExecutorImpl$3.call(TaskExecutorImpl.java:288)
error	08-сен-2015 14:19:52		at com.atlassian.bamboo.task.TaskExecutorImpl$3.call(TaskExecutorImpl.java:284)
error	08-сен-2015 14:19:52		at com.atlassian.bamboo.task.TaskExecutorImpl.executeTaskWithPrePostActions(TaskExecutorImpl.java:200)
error	08-сен-2015 14:19:52		at com.atlassian.bamboo.task.TaskExecutorImpl.executeTasks(TaskExecutorImpl.java:284)
error	08-сен-2015 14:19:52		at com.atlassian.bamboo.task.TaskExecutorImpl.execute(TaskExecutorImpl.java:106)
error	08-сен-2015 14:19:52		at com.atlassian.bamboo.build.pipeline.tasks.ExecuteBuildTask.call(ExecuteBuildTask.java:75)
error	08-сен-2015 14:19:52		at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build(DefaultBuildAgent.java:196)
error	08-сен-2015 14:19:52		at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl$1.call(BuildAgentControllerImpl.java:124)
error	08-сен-2015 14:19:52		at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl$1.call(BuildAgentControllerImpl.java:115)
error	08-сен-2015 14:19:52		at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:215)
error	08-сен-2015 14:19:52		at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild(BuildAgentControllerImpl.java:114)
error	08-сен-2015 14:19:52		at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent$1.run(DefaultBuildAgent.java:118)
error	08-сен-2015 14:19:52		at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:49)
error	08-сен-2015 14:19:52		at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:31)
error	08-сен-2015 14:19:52		at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:20)
error	08-сен-2015 14:19:52		at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:52)
error	08-сен-2015 14:19:52		at java.lang.Thread.run(Thread.java:745)
simple	08-сен-2015 14:19:52	Finalising the build...
simple	08-сен-2015 14:19:52	Stopping timer.
simple	08-сен-2015 14:19:52	Build 11468801-11534337-11894786 completed.
simple	08-сен-2015 14:19:52	Finished processing deployment result Deployment of 'release-1' on 'Staging'
```

Bamboo 5.9.1 build 5914 
Bamboozled 5.10.1

**Comment by rosskevin** [comment]
Hi @panasyuk, thank you for reporting.  I saw an obvious opportunity for a NullPointerException in the code, I've deployed `5.10.2` for you to try.  I'm pretty sure this should solve your problem, if not, please reopen this issue.  Thank you

**Comment by rosskevin** [comment]
Actually, I think this may still fail, looking at one more thing...

**Comment by panasyuk** [comment]
@rosskevin Ok, let me know if i can help you.

**Comment by rosskevin** [comment]
5.10.3 is published, please give that a shot and let me know if it solves your issue.

**Comment by panasyuk** [comment]
Thanks, your commits solved the issue.

ср, 9 сент. 2015, 0:00, Kevin Ross <notifications@github.com>:
