### ISSUE TITLE
Error while detecting ruby version on windows

### ISSUE THREAD

**Issue by tommywo** [alienfast/bamboozled-ruby-plugin#16]
```
java.lang.IllegalArgumentException: Unable to parse ruby version string.
	at com.alienfast.bamboozled.ruby.rt.system.SystemRubyUtils.parseRubyVersionString(SystemRubyUtils.java:26)
	at com.alienfast.bamboozled.ruby.rt.windows.WindowsRubyLocator.listRubyRuntimes(WindowsRubyLocator.java:121)
```
ruby --version output is:
ruby 1.9.3p551 (2014-11-13) [i386-mingw32]

**Comment by rosskevin** [comment]
Hi there, I don't have a windows machine so unfortunately cannot help.  I'm happy to accept a PR. 

Here's how to get started with development: https://github.com/alienfast/bamboozled-ruby-plugin/wiki/Development
