### ISSUE TITLE
Path for xbvf seems to be mandatory

### ISSUE THREAD

**Issue by testzugang** [alienfast/bamboozled-ruby-plugin#7]
We use Bamboo on Mac OS Yosemite and I want to run rake test on a gem so I only checked "bundle exec" in the configuration but it seems that the xbvf path is mandatory instead of optional. Running the job results in a null pointer exception for the capability.

```
Starting task 'Minitest' of type 'com.alienfast.bamboozled.ruby.bamboozled-ruby-plugin:task.rake'
error	02-Mar-2015 12:43:58	Error occurred while running Task 'Minitest(3)' of type com.alienfast.bamboozled.ruby.bamboozled-ruby-plugin:task.rake.
error	02-Mar-2015 12:43:58	java.lang.NullPointerException: Capability
error	02-Mar-2015 12:43:58		at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:204)
error	02-Mar-2015 12:43:58		at com.alienfast.bamboozled.ruby.tasks.rake.RakeTask.getXvfbRunExecutablePath(RakeTask.java:70)
error	02-Mar-2015 12:43:58		at com.alienfast.bamboozled.ruby.tasks.rake.RakeTask.buildCommandList(RakeTask.java:49)
error	02-Mar-2015 12:43:58		at com.alienfast.bamboozled.ruby.tasks.AbstractRubyTask.execute(AbstractRubyTask.java:90)
error	02-Mar-2015 12:43:58		at com.atlassian.bamboo.task.TaskExecutorImpl.executeTasks(TaskExecutorImpl.java:220)
error	02-Mar-2015 12:43:58		at com.atlassian.bamboo.task.TaskExecutorImpl.execute(TaskExecutorImpl.java:98)
error	02-Mar-2015 12:43:58		at com.atlassian.bamboo.build.pipeline.tasks.ExecuteBuildTask.call(ExecuteBuildTask.java:75)
error	02-Mar-2015 12:43:58		at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build(DefaultBuildAgent.java:188)
error	02-Mar-2015 12:43:58		at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild(BuildAgentControllerImpl.java:112)
error	02-Mar-2015 12:43:58		at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent$1.run(DefaultBuildAgent.java:110)
error	02-Mar-2015 12:43:58		at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:49)
error	02-Mar-2015 12:43:58		at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:31)
error	02-Mar-2015 12:43:58		at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:20)
error	02-Mar-2015 12:43:58		at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:52)
error	02-Mar-2015 12:43:58		at java.lang.Thread.run(Thread.java:695)
´´´

**Comment by rosskevin** [comment]
New version [uploaded](https://marketplace.atlassian.com/plugins/com.alienfast.bamboozled.ruby.bamboozled-ruby-plugin) with the fixes, or you can just auto update from the UPM.

**Comment by testzugang** [comment]
Thanks a lot for the quick response and fix. Will check it out!
